In [1]:
import pandas as pd

In [2]:
employees = {
    "Name": ["Tanir", "Rahul", "Ananya", "Priya"],
    "Age": [24, 27, 22, 25],
    "Department": ["AI", "Backend", "HR", "AI"],
    "Salary": [70000, 85000, 50000, 72000]
}

In [3]:
df = pd.DataFrame(employees)

In [4]:
df

     Name  Age Department  Salary
0   Tanir   24         AI   70000
1   Rahul   27    Backend   85000
2  Ananya   22         HR   50000
3   Priya   25         AI   72000

In [5]:
df.head()

     Name  Age Department  Salary
0   Tanir   24         AI   70000
1   Rahul   27    Backend   85000
2  Ananya   22         HR   50000
3   Priya   25         AI   72000

In [6]:
df.tail()

     Name  Age Department  Salary
0   Tanir   24         AI   70000
1   Rahul   27    Backend   85000
2  Ananya   22         HR   50000
3   Priya   25         AI   72000

In [7]:
df.shape

(4, 4)

In [8]:
df.columns

Index(['Name', 'Age', 'Department', 'Salary'], dtype='str')

In [9]:
df["Name"]

0     Tanir
1     Rahul
2    Ananya
3     Priya
Name: Name, dtype: str

In [10]:
df[['Name' , 'Age']]

     Name  Age
0   Tanir   24
1   Rahul   27
2  Ananya   22
3   Priya   25

In [11]:
df[df["Department"] == 'AI']

    Name  Age Department  Salary
0  Tanir   24         AI   70000
3  Priya   25         AI   72000

In [13]:
df["Bonus"] = df["Salary"] * 0.10

In [14]:
df

     Name  Age Department  Salary   Bonus
0   Tanir   24         AI   70000  7000.0
1   Rahul   27    Backend   85000  8500.0
2  Ananya   22         HR   50000  5000.0
3   Priya   25         AI   72000  7200.0

In [16]:
df.sort_values("Age")

     Name  Age Department  Salary   Bonus
2  Ananya   22         HR   50000  5000.0
0   Tanir   24         AI   70000  7000.0
3   Priya   25         AI   72000  7200.0
1   Rahul   27    Backend   85000  8500.0

In [17]:
df = df.sort_values("Salary")

In [18]:
df

     Name  Age Department  Salary   Bonus
2  Ananya   22         HR   50000  5000.0
0   Tanir   24         AI   70000  7000.0
3   Priya   25         AI   72000  7200.0
1   Rahul   27    Backend   85000  8500.0

In [20]:
df.sort_values("Salary" , ascending=False)

     Name  Age Department  Salary   Bonus
1   Rahul   27    Backend   85000  8500.0
3   Priya   25         AI   72000  7200.0
0   Tanir   24         AI   70000  7000.0
2  Ananya   22         HR   50000  5000.0

In [21]:
dirty_data = {
    "Name": ["Tanir", "Rahul", None, "Priya"],
    "Age": [24, None, 22, 25],
    "Salary": [70000, 85000, None, 72000]
}

In [24]:
dirty_df = pd.DataFrame(dirty_data)

In [25]:
dirty_df

    Name   Age   Salary
0  Tanir  24.0  70000.0
1  Rahul   NaN  85000.0
2    NaN  22.0      NaN
3  Priya  25.0  72000.0

In [26]:
dirty_df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2   True  False    True
3  False  False   False

In [27]:
dirty_df.isnull().sum()

Name      1
Age       1
Salary    1
dtype: int64

In [28]:
dirty_df.dropna()

    Name   Age   Salary
0  Tanir  24.0  70000.0
3  Priya  25.0  72000.0

In [29]:
dirty_df["Age"].fillna(dirty_df["Age"].mean())

0    24.000000
1    23.666667
2    22.000000
3    25.000000
Name: Age, dtype: float64

In [30]:
df.groupby("Department")["Salary"].mean()

Department
AI         71000.0
Backend    85000.0
HR         50000.0
Name: Salary, dtype: float64